### ISSUE TITLE
Добавьте математические функции в область видимости

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2019-13-graphs#11]
Добавьте себе в программу
```JavaScript
let sin = Math.sin;
let sqrt = Math.sqrt;
...
```
Тогда можно будет в выражении для функции писать `sin`, `cos` и т.д. без `Math.`. Можно также добавить `tg` и `ctg` для, соответственно, тангенсов и котангенсов.

**Comment by Ana-Lyako** [comment]
Добавили

**Comment by Mazdaywik** [comment]
Я имел ввиду
```JavaScript
let tg = Math.tan;
let ctg = (x) => { return 1/tg(x) }
```
Чтобы можно было тангенс и котангенс писать в отечественной математической традиции: `tg` и `ctg`. Ещё можно добавить синоним `ln` для натурального логарифма.

Также можно ввести константу `PI`:
```JavaScript
const PI = Math.PI;
const π = PI;
```
Насколько помню, JavaScript допускает любые юникодовские буквы в именах, поэтому `π` — нормальное имя для переменной.

**Comment by Ana-Lyako** [comment]
Исправили

**Comment by Mazdaywik** [comment]
Вообще, я имел ввиду, что логарифм можно писать и `log`, и `ln`, но это не важно.

Забыл вам напомнить, что в комментарии к коммитам можно добавлять номер заявки, которую они решают. Например, для коммита 5664a09c6b7157bd4c5b853d0416899fec45d249 можно было написать
```
Работа математических функций без Math в объявлении и число пи - обновлено (#11)
```
и тогда бы коммит «пришился» бы к этой заявке. Вообще, я это говорил на лекции, но за столько времени оно забылось.
