### ISSUE TITLE
Плотность точек

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2019-13-graphs#3]
Попробуйте ввести функцию `1/x`. «Рога» гиперболы, уходящие влево-вправо, сплошные. «Рога», уходящие вверх-вниз — пунктиром, причём очень редким.

Почему? Очевидно, потому что шаг фиксированный.

Сами придумаете, как решить проблему гиперболы, или мне подсказать?

А вот более жёсткий тестовый пример:
```JavaScript
Math.sin(1/x)
```

**Comment by Marina-Glush** [comment]
Уже решаю проблему

**Comment by Mazdaywik** [comment]
На `Math.sin(1/x)` зависает.
