### ISSUE TITLE
Пулл реквест нельзя слить с основным проектом даже после одобрения

### ISSUE THREAD

**Issue by Ana-Lyako** [bmstu-iu9/utp2019-13-graphs#7]
@Mazdaywik, не знаете, с чем это может быть связано?

**Comment by Mazdaywik** [comment]
Знаю, с чем это связано. @Marina-Glush не взяла себе прав на запись. Поэтому её ревью пока ничего не значит.

Права на запись есть только у команды @bmstu-iu9/utp-2019. Я её звал в команду, но она в неё ещё не вступила.

Всё просто. @Marina-Glush просто забыла принять приглашение. К ней на почту и в нотификации (<https://github.com/notifications>) должно прийти приглашение, где нужно нажать на кнопку «Принять приглашение». Вы приглашение приняли, а она что-то проглядела.

**Comment by Marina-Glush** [comment]
Да,  проглядела. Спасибо за ответ, я исправилась

**Comment by Mazdaywik** [comment]
Замечательно! Вижу слитый #6.

Проблема решена, заявку закрываю.
